language: java
sudo: false
cache:
  directories:
  - $HOME/.m2

install:
  - mvn install -Ptravis -DskipTests=true -Dmaven.javadoc.skip=true -Dlog4j.configuration= -B -V -q

script:
  - mvn test -Dlog4j.configuration= -q
